### PR TITLE
Add Python 3.6 and coveralls

### LINKED ISSUE #6: Add support for Python 3.6
And modernize/standardize tox.ini/.travis.yml. (I don't see any reason we can't use coverage and zope.testrunner here too. I mean, there's not much to cover, but still. That wouldn't seem to introduce any circular dependencies.)

### PR DESCRIPTION
**Pull request by jamadden**
Drop python 3.3.

Minor misc project gardening.

Fixes #6

### CODE REVIEW

**Comment by tseaver** [comment]
In "days of yore", we avoided adding deps in the "bottom-most" ZTK packages (`zope.event`, `zope.interface`, `zope.component`, etc.) to stuff like `zope.testrunner` / `zope.testing` because they did indeed depend on one or more of them.  If they no longer do so, then this should be fine.

**Comment by jamadden** [comment]
That completely makes sense to me! Circular dependencies are a special kind of torment, even in teat code. I worked hard to remove them recently in a lot of zope.app and other packages. I did a cursory check for the packages involved here and didn’t find anything (nothing low level depends on zope.event). I can look into presenting a more precise dependency graph.

**Comment by jamadden** [comment]
Here's what `pipdeptree` says:
```
zope.event==4.2.1.dev0
  - setuptools [required: Any, installed: 36.0.1]
zope.testing==4.6.2
  - setuptools [required: Any, installed: 36.0.1]
zope.testrunner==4.7.0
  - setuptools [required: Any, installed: 36.0.1]
  - six [required: Any, installed: 1.10.0]
  - zope.exceptions [required: Any, installed: 4.1.0]
    - setuptools [required: Any, installed: 36.0.1]
    - zope.interface [required: Any, installed: 4.4.2]
      - setuptools [required: Any, installed: 36.0.1]
  - zope.interface [required: Any, installed: 4.4.2]
    - setuptools [required: Any, installed: 36.0.1]
```

So it looks like we're clear.

**Comment by jamadden** [comment]
Thank you!

**Pull request merged**
