### PR TITLE
Add synchronous behaviour to docs

### PR DESCRIPTION
**Pull request by asaf-kali**
See #15

### CODE REVIEW

**Review by mgedmin — APPROVED** [review]
LGTM

**Comment by mgedmin** [comment]
(I don't know if I can hit the merge button; we have a contributor agreement requirement, but maybe the patch is too trivial to be considered copyrightable?  IANAL.)

**Comment by jamadden** [comment]
For documentation changes, [Plone's guidelines don't require a signed contributor agreement](https://docs.plone.org/about/license.html): 

> [A]ll we need is your written confirmation that you are agreeing your contribution can be under Creative Commons.
>
> You can also add in a comment with your pull request “I, `<full name>`, agree to have this published under Creative Commons 4.0 International BY”.

I don't know how we're considering the zopefoundation documentation licensed these days (if it ever was), but I'd be ok merging this if @asaf-kali could write that comment here.

**Comment by asaf-kali** [comment]
I, Asaf Kali, agree to have this published under Creative Commons 4.0 International BY.

**Comment by icemac** [comment]
Thank you!

**Pull request merged**
